# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceship.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspaceship.proto\"\xdf\x03\n\tSpaceship\x12,\n\talignment\x18\x01 \x01(\x0e\x32\x14.Spaceship.AlignmentH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12%\n\x06\x63lass_\x18\x04 \x01(\x0e\x32\x10.Spaceship.ClassH\x02\x88\x01\x01\x12\x13\n\x06length\x18\x03 \x01(\x02H\x03\x88\x01\x01\x12\x16\n\tcrew_size\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x12\n\x05\x61rmed\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.Spaceship.Officer\x1a>\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\" \n\tAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"\\\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\x42\x0c\n\n_alignmentB\x07\n\x05_nameB\t\n\x07_class_B\t\n\x07_lengthB\x0c\n\n_crew_sizeB\x08\n\x06_armed\"!\n\x0b\x43oordinates\x12\x12\n\ncoordinate\x18\x01 \x03(\x02\x32\x41\n\x10SpaceshipService\x12-\n\rGetSpaceships\x12\x0c.Coordinates\x1a\n.Spaceship\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPACESHIP']._serialized_start=20
  _globals['_SPACESHIP']._serialized_end=499
  _globals['_SPACESHIP_OFFICER']._serialized_start=240
  _globals['_SPACESHIP_OFFICER']._serialized_end=302
  _globals['_SPACESHIP_ALIGNMENT']._serialized_start=304
  _globals['_SPACESHIP_ALIGNMENT']._serialized_end=336
  _globals['_SPACESHIP_CLASS']._serialized_start=338
  _globals['_SPACESHIP_CLASS']._serialized_end=430
  _globals['_COORDINATES']._serialized_start=501
  _globals['_COORDINATES']._serialized_end=534
  _globals['_SPACESHIPSERVICE']._serialized_start=536
  _globals['_SPACESHIPSERVICE']._serialized_end=601
# @@protoc_insertion_point(module_scope)
